# For local development use only
FROM swift:5.6-focal AS swift-builder

WORKDIR /app

SHELL ["/bin/bash", "-c"]

RUN set -ex \
    && apt update \
    && apt install libssl-dev libcurl4 git jq curl make ca-certificates dumb-init -y \
    && apt autoremove -y \
    && apt autoclean -y

RUN set -ex \
    && export TOOLBOX_VERSION=$(curl -sSL https://api.github.com/repos/vapor/toolbox/releases/latest | jq -r .tag_name) \
    && git clone --depth 1 --branch ${TOOLBOX_VERSION} https://github.com/vapor/toolbox.git \
    && (cd toolbox && make -j $(nproc) install)

# The environment variable is set to empty(use the default value)
ARG HOST_ORIGIN
ARG BASE_PREFIX
ARG GOOGLE_ANALYTICS_UID

EXPOSE 8080/tcp

VOLUME /app

# Add dump-init to ensure container can respond to exit signals
ENTRYPOINT ["/usr/bin/dumb-init", "--"]

CMD ["vapor", "run"]
