var app = require("../app");


/*
 * GET home page.
 */

exports.index = function(req, res){
  res.render('index', { title: 'Gitignore.io' });
};

/*
 * GET API page.
 */

exports.apiIgnore = function(req, res){
//  console.log(req.params.ignore);
  var ignoreFileList = req.params.ignore.split(",");
  var output = "# Generated by http://gitignore.io\n";
  for (var file in ignoreFileList){
    if (app.gitIgnoreJSONObject[ignoreFileList[file]] == undefined){
      output += "\n#!! ERROR: " + ignoreFileList[file] + " is undefined. Use list command to see defined gitignore types !!#\n"
    } else {
      output += "\n### " + app.gitIgnoreJSONObject[ignoreFileList[file]].name + " ###\n"
      output += app.gitIgnoreJSONObject[ignoreFileList[file]].contents;
    }
  }
  res.setHeader('Content-Type', 'text/plain');
  res.setHeader('Expires', '0');
  res.send(output);
};
/*
 * GET List of all ignore types
 */
exports.apiListTypes = function(req, res){
  res.setHeader('Content-Type', 'text/plain');
  res.send(app.gitIgnoreJSONString);
};
